apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: app-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
      - name: nginx-containers
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: frontend
