apiVersion: v1
kind: ReplicationController
metadata:
  name: app-rc
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: app-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
