apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-dashboard
spec:
  containers:
    - name: kubernetes-dashboard
      image: kubernetes-dashboard
  serviceAccountName: dashboard-sa
# automountServiceAccountToken: false
