apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - image: data-processor
    name: data-processor
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            operator: In
            values:
            - Large
