apiVersion: v1
kind: Pod
metadata:
  name: simple-app
spec:
  containers:
    - name: simple-app
      image: simple-app
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /api/ready
          port: 8080
      livenessProbe:
        httpGet:
          path: /api/healthy
          port: 8080
